#!/usr/bin/env python3
"""Parse Asian Games shooting page JSONL into semantic row-level JSONL.

This is a second-stage parser. It consumes the page-level JSONL generated by
extract_pdfs_to_jsonl.py and emits canonical athlete/result records with source
page metadata and an audit record for every required page.
"""

from __future__ import annotations

import argparse
import json
import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Iterable


DEFAULT_INPUT_DIR = Path("asian_games/jsonl")
DEFAULT_OUTPUT_DIR = Path("asian_games/parsed")

INPUT_FILES = ("asian_games_2018.jsonl", "asian_games_2022.jsonl")
REQUIRED_RANGES = {
    2018: {
        "Entry List by NOC": range(15, 29),
        "Results": range(39, 90),
    },
    2022: {
        "ASC Ranking Points Results": range(29, 41),
        "Results": range(41, 130),
    },
}

DATE_RE = re.compile(
    r"\b(?:MON|TUE|WED|THU|FRI|SAT|SUN)\s+\d{1,2}\s+[A-Z]{3}\s+\d{4}\b"
)
NOC_BLOCK_RE = re.compile(r"^\s*([A-Z]{3})\s+-\s+(.+?)\s+Total:\s*(\d+)\s*$")
ENTRY_ATHLETE_RE = re.compile(
    r"^\s*(?P<name>.+?)\s{2,}(?P<bib>\d{4})\s+"
    r"(?P<gender>[MF])\s+(?P<dob>\d{1,2}\s+[A-Z]{3}\s+\d{4})"
    r"(?:\s+(?P<ds>[A-Z]+))?\s{2,}(?P<event>.+?)\s*$"
)
RANKING_ROW_RE = re.compile(
    r"^\s*(?P<rank>\d+)\s+(?P<rating>\d+)\s+(?P<name>.+?)\s+"
    r"(?P<birth>\d{2}\s+[A-Za-z]{3}\s+\d{4})\s+(?P<noc>[A-Z]{3})\s*$"
)
RANK_LINE_RE = re.compile(r"^\s*(?P<rank>\d{1,3})\s+(?P<body>.+?)\s*$")
TEAM_DASH_RE = re.compile(r"^(?P<noc>[A-Z]{3})\s+-\s+(?P<team>.+?)\s+(?P<scores>[-\d].*)$")
TEAM_NOC_AFTER_RE = re.compile(r"^(?P<team>[A-Za-z][A-Za-z .'/&-]+?)\s+(?P<noc>[A-Z]{3})\s+(?P<scores>[-\d].*)$")
INDIVIDUAL_RE = re.compile(r"^(?P<bib>\d{3,4})\s+(?P<rest>.+)$")
NOISE_PREFIXES = (
    "Legend:",
    "Timing and Results provided",
    "Report Created",
    "Records",
    "Record ",
    "WR ",
    "QWR ",
    "QGR ",
    "QAsR ",
    "AsR ",
    "GR ",
    "A ",
    "F  Female",
    "No. Number",
)
ROUND_DETAIL_LINES = {
    "Gold Medal Match",
    "Bronze Medal Match",
    "Semifinal 1",
    "Semifinal 2",
    "Semifinals",
}


@dataclass
class PendingResult:
    record: dict[str, Any]
    detail_lines: list[str] = field(default_factory=list)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Parse Asian Games page JSONL into athlete and result JSONL."
    )
    parser.add_argument(
        "--input-dir",
        type=Path,
        default=DEFAULT_INPUT_DIR,
        help=f"Directory containing page JSONL files. Default: {DEFAULT_INPUT_DIR}",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=DEFAULT_OUTPUT_DIR,
        help=f"Directory for parsed outputs. Default: {DEFAULT_OUTPUT_DIR}",
    )
    return parser.parse_args()


def clean_cell(value: Any) -> str:
    if value is None:
        return ""
    return re.sub(r"\s+", " ", str(value).replace("\n", " ")).strip()


def compact(value: str) -> str:
    return re.sub(r"\s+", " ", value).strip()


def text_lines(page: dict[str, Any]) -> list[str]:
    return [line.rstrip() for line in page["content"]["text"].splitlines() if line.strip()]


def visible(line: str) -> str:
    return compact(line)


def games_year(page: dict[str, Any]) -> int:
    name = page["source"]["pdf_file_name"]
    match = re.search(r"(20\d{2})", name)
    if not match:
        raise ValueError(f"Cannot infer games year from {name}")
    return int(match.group(1))


def required_page_type(year: int, page_number: int, text: str) -> str | None:
    for page_type, page_range in REQUIRED_RANGES.get(year, {}).items():
        if page_number in page_range:
            return page_type
    return None


def source_base(page: dict[str, Any], page_type: str) -> dict[str, Any]:
    year = games_year(page)
    return {
        "games_year": year,
        "source_pdf": page["source"]["pdf_file_name"],
        "source_page": page["page"]["page_number"],
        "page_type": page_type,
    }


def is_noise_line(line: str) -> bool:
    stripped = visible(line)
    if not stripped:
        return True
    if stripped.startswith(NOISE_PREFIXES):
        return True
    if stripped.startswith("SHO") and "Report Created" in stripped:
        return True
    if "Timing and Results provided" in stripped:
        return True
    if stripped in {"Results", "比赛成绩", "Shooting", "射击"}:
        return True
    return False


def extract_event_round(page: dict[str, Any], page_type: str) -> tuple[str | None, str | None]:
    lines = [visible(line) for line in text_lines(page)]
    if page_type == "Entry List by NOC":
        return None, None

    if page_type == "ASC Ranking Points Results":
        for index, line in enumerate(lines):
            if "Rank Rating Name Birth Nation" in line and index > 0:
                for candidate in reversed(lines[:index]):
                    if (
                        candidate
                        and "ASC RANKING" not in candidate
                        and "This is only" not in candidate
                    ):
                        return candidate, None
        for candidate in lines:
            if re.search(r"\b(?:Men|Women|Team)\b", candidate):
                return candidate, None
        return None, None

    before_results: list[str] = []
    for line in lines:
        if line in {"Results", "比赛成绩"}:
            break
        before_results.append(line)

    cleaned: list[str] = []
    for line in before_results:
        if not line or line in {"Shooting", "射击", "Fuyang Yinhu Sports Centre", "富阳银湖体育中心"}:
            continue
        if DATE_RE.search(line):
            line = DATE_RE.sub("", line).strip()
        line = re.sub(r"\bStart Time\s+\d{1,2}:\d{2}\b", "", line).strip()
        line = line.replace("决赛", "").replace("资格赛", "").replace("第二阶段", "").strip()
        if line:
            cleaned.append(line)

    round_keywords = (
        "Finals Bronze Medal Match 1",
        "Finals Bronze Medal Match 2",
        "Finals Gold Medal Match",
        "Qualifications Rapid",
        "Qualifications Stage 2",
        "Qualification",
        "Medal Matches",
        "Competition",
        "Final",
    )
    round_name: str | None = None
    event: str | None = None
    previous_meaningful: str | None = None
    for line in cleaned:
        for keyword in round_keywords:
            if keyword in line:
                round_name = keyword
                event = compact(line.replace(keyword, ""))
                if not event:
                    event = previous_meaningful
                break
        if round_name:
            break
        if re.search(r"\b(?:Men|Women|Team)\b", line):
            previous_meaningful = line

    if event:
        return event, round_name

    meaningful = [
        line
        for line in cleaned
        if not re.search(r"^[A-Z]{3}\b", line)
        and not re.search(r"^\d{1,2}\s+[A-Z]{3}\b", line)
    ]
    if len(meaningful) >= 2:
        return meaningful[-2], meaningful[-1]
    if meaningful:
        return meaningful[-1], None
    return None, None


def write_jsonl(path: Path, records: Iterable[dict[str, Any]]) -> int:
    count = 0
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as output:
        for record in records:
            output.write(json.dumps(record, ensure_ascii=False, separators=(",", ":")))
            output.write("\n")
            count += 1
    return count


def load_pages(input_dir: Path) -> list[dict[str, Any]]:
    pages: list[dict[str, Any]] = []
    for file_name in INPUT_FILES:
        path = input_dir / file_name
        if not path.exists():
            raise FileNotFoundError(f"Missing page JSONL input: {path}")
        with path.open(encoding="utf-8") as file_obj:
            for line in file_obj:
                if line.strip():
                    pages.append(json.loads(line))
    return pages


def parse_entry_list(page: dict[str, Any]) -> tuple[list[dict[str, Any]], list[str]]:
    records: list[dict[str, Any]] = []
    warnings: list[str] = []
    current_noc_code: str | None = None
    current_noc_name: str | None = None
    current_record: dict[str, Any] | None = None

    def finish_current() -> None:
        nonlocal current_record
        if current_record:
            current_record["events"] = [event for event in current_record["events"] if event]
            records.append(current_record)
            current_record = None

    for raw_line in text_lines(page):
        line = raw_line.rstrip()
        if is_noise_line(line) or "Entry List by NOC" in line or "Date of Birth" in line:
            continue

        noc_match = NOC_BLOCK_RE.match(line)
        if noc_match:
            finish_current()
            current_noc_code = noc_match.group(1)
            current_noc_name = noc_match.group(2).strip()
            continue

        athlete_match = ENTRY_ATHLETE_RE.match(line)
        if athlete_match and current_noc_code:
            finish_current()
            current_record = {
                "record_type": "athlete",
                **source_base(page, "Entry List by NOC"),
                "noc_code": current_noc_code,
                "noc_name": current_noc_name,
                "athlete_name": compact(athlete_match.group("name")),
                "bib_no": athlete_match.group("bib"),
                "gender": athlete_match.group("gender"),
                "date_of_birth": athlete_match.group("dob"),
                "ds": athlete_match.group("ds"),
                "events": [compact(athlete_match.group("event"))],
                "raw_row": visible(line),
                "parser_confidence": "high",
            }
            continue

        stripped = visible(line)
        if current_record and stripped and not re.search(r"\d{4}\s+[MF]\s+\d{1,2}\s+[A-Z]{3}\s+\d{4}", stripped):
            if not stripped.startswith(("Page ", "SHO-")) and not NOC_BLOCK_RE.match(line):
                current_record["events"].append(stripped)
                current_record["raw_row"] += " | " + stripped

    finish_current()
    if not records:
        warnings.append("no_entry_records")
    return records, warnings


def parse_ranking_page(page: dict[str, Any]) -> tuple[list[dict[str, Any]], list[str]]:
    event, _ = extract_event_round(page, "ASC Ranking Points Results")
    records: list[dict[str, Any]] = []
    warnings: list[str] = []
    for line in text_lines(page):
        match = RANKING_ROW_RE.match(line)
        if not match:
            continue
        records.append(
            {
                "record_type": "athlete",
                **source_base(page, "ASC Ranking Points Results"),
                "event": event,
                "rank": match.group("rank"),
                "rating": match.group("rating"),
                "athlete_name": compact(match.group("name")),
                "date_of_birth": match.group("birth"),
                "noc_code": match.group("noc"),
                "noc_name": None,
                "bib_no": None,
                "gender": None,
                "ds": None,
                "events": [event] if event else [],
                "raw_row": visible(line),
                "parser_confidence": "high",
            }
        )
    if not records:
        warnings.append("no_ranking_records")
    return records, warnings


def score_tokens(text: str) -> list[str]:
    return re.findall(r"\b(?:DNS|DSQ|DNF|[\d]+(?:\.\d+)?(?:-\d+x)?)\b", text)


def extract_total(rest: str) -> str | None:
    tokens = score_tokens(rest)
    return tokens[-1] if tokens else None


def extract_remarks(rest: str, total: str | None) -> str | None:
    if not total:
        return None
    index = rest.rfind(total)
    if index < 0:
        return None
    remarks = compact(rest[index + len(total) :])
    return remarks or None


def parse_name_noc_scores(rest: str) -> tuple[str, str | None, str]:
    match = re.match(r"(?P<name>.+?)\s+(?P<noc>[A-Z]{3})\s+(?P<scores>.+)$", rest)
    if match:
        return compact(match.group("name")), match.group("noc"), compact(match.group("scores"))
    return compact(rest), None, ""


def is_team_result_line(body: str) -> bool:
    return bool(TEAM_DASH_RE.match(body) or TEAM_NOC_AFTER_RE.match(body))


def parse_team_line(body: str) -> tuple[str | None, str | None, str]:
    dash = TEAM_DASH_RE.match(body)
    if dash:
        return dash.group("noc"), compact(dash.group("team")), compact(dash.group("scores"))
    after = TEAM_NOC_AFTER_RE.match(body)
    if after:
        return after.group("noc"), compact(after.group("team")), compact(after.group("scores"))
    return None, None, body


def split_team_athlete(rest: str) -> tuple[str, str | None, str]:
    gender = None
    gender_match = re.match(r"(?P<name>.+?)\s+(?P<gender>[MF])\s+(?P<scores>[-\d].*)$", rest)
    if gender_match:
        return (
            compact(gender_match.group("name")),
            gender_match.group("gender"),
            compact(gender_match.group("scores")),
        )
    score_start = re.search(r"\s[-\d]+(?:\.\d+)?\b", rest)
    if not score_start:
        return compact(rest), gender, ""
    return compact(rest[: score_start.start()]), gender, compact(rest[score_start.start() :])


def result_record(
    page: dict[str, Any],
    event: str | None,
    round_name: str | None,
    rank: str,
    raw_row: str,
    *,
    bib_no: str | None = None,
    athlete_name: str | None = None,
    noc_code: str | None = None,
    team_name: str | None = None,
    gender: str | None = None,
    total: str | None = None,
    individual_total: str | None = None,
    remarks: str | None = None,
    score_detail: dict[str, Any] | None = None,
    confidence: str = "high",
) -> dict[str, Any]:
    return {
        "record_type": "result",
        **source_base(page, "Results"),
        "event": event,
        "round": round_name,
        "rank": rank,
        "bib_no": bib_no,
        "athlete_name": athlete_name,
        "noc_code": noc_code,
        "team_name": team_name,
        "gender": gender,
        "total": total,
        "individual_total": individual_total,
        "score_detail": score_detail or {},
        "remarks": remarks,
        "raw_row": raw_row,
        "parser_confidence": confidence,
    }


def finalize_pending(pending: PendingResult | None, records: list[dict[str, Any]]) -> None:
    if not pending:
        return
    if pending.detail_lines:
        pending.record["score_detail"]["detail_lines"] = pending.detail_lines
        raw_detail = " | ".join(pending.detail_lines)
        updated_total = extract_total(raw_detail)
        if updated_total and not pending.record.get("team_name"):
            pending.record["total"] = updated_total
    records.append(pending.record)


def parse_results_page(page: dict[str, Any]) -> tuple[list[dict[str, Any]], list[str]]:
    event, round_name = extract_event_round(page, "Results")
    records: list[dict[str, Any]] = []
    warnings: list[str] = []
    current_team: dict[str, Any] | None = None
    pending: PendingResult | None = None
    round_detail: str | None = None

    for raw_line in text_lines(page):
        line = visible(raw_line)
        if not line or is_noise_line(line):
            continue
        if line in ROUND_DETAIL_LINES:
            round_detail = line
            continue
        if any(header in line for header in ("Rank Name", "Rank No.", "Bib NOC", "No. Code")):
            continue
        if re.match(r"^(?:Rank|Bib|No\.|Code|Name|Total|Remarks)\b", line):
            continue

        rank_match = RANK_LINE_RE.match(line)
        if rank_match:
            rank = rank_match.group("rank")
            body = compact(rank_match.group("body"))
            if is_team_result_line(body):
                finalize_pending(pending, records)
                pending = None
                noc_code, team_name, scores = parse_team_line(body)
                total = extract_total(scores)
                current_team = {
                    "rank": rank,
                    "noc_code": noc_code,
                    "team_name": team_name,
                    "total": total,
                    "remarks": extract_remarks(scores, total),
                    "raw_row": line,
                    "score_detail": {
                        "team_scores": score_tokens(scores),
                        **({"round_detail": round_detail} if round_detail else {}),
                    },
                }
                continue

            individual = INDIVIDUAL_RE.match(body)
            if individual:
                finalize_pending(pending, records)
                pending = None
                current_team = None
                bib_no = individual.group("bib")
                name, noc_code, scores = parse_name_noc_scores(individual.group("rest"))
                total = extract_total(scores)
                pending = PendingResult(
                    record=result_record(
                        page,
                        event,
                        round_name,
                        rank,
                        line,
                        bib_no=bib_no,
                        athlete_name=name,
                        noc_code=noc_code,
                        total=total,
                        remarks=extract_remarks(scores, total),
                        score_detail={
                            "scores": score_tokens(scores),
                            **({"round_detail": round_detail} if round_detail else {}),
                        },
                    )
                )
                continue

        if current_team:
            athlete = INDIVIDUAL_RE.match(line)
            if athlete:
                bib_no = athlete.group("bib")
                name, gender, scores = split_team_athlete(athlete.group("rest"))
                individual_total = extract_total(scores)
                records.append(
                    result_record(
                        page,
                        event,
                        round_name,
                        current_team["rank"],
                        current_team["raw_row"] + " | " + line,
                        bib_no=bib_no,
                        athlete_name=name,
                        noc_code=current_team["noc_code"],
                        team_name=current_team["team_name"],
                        gender=gender,
                        total=current_team["total"],
                        individual_total=individual_total,
                        remarks=current_team["remarks"],
                        score_detail={
                            **current_team["score_detail"],
                            "individual_scores": score_tokens(scores),
                        },
                    )
                )
                continue

        if pending and not RANK_LINE_RE.match(line):
            if not line.startswith(("Page ", "SHO")):
                pending.detail_lines.append(line)

    finalize_pending(pending, records)

    # Some medal-match pages are split into separate small extracted tables. The
    # text parser above handles the visible rows; this fallback captures table
    # rows that have rank-bearing data but no usable line layout.
    if not records:
        for table in page["content"].get("tables", []):
            for row in table.get("rows", []):
                cells = [clean_cell(cell) for cell in row if clean_cell(cell)]
                if not cells:
                    continue
                packed_rank = re.match(r"^(?P<rank>\d{1,3})\s+(?P<team>[^\n]+)(?:\n(?P<athletes>.*))?$", str(row[0] or ""), re.S)
                if packed_rank and len(cells) >= 2:
                    rank = packed_rank.group("rank")
                    team_name = compact(packed_rank.group("team"))
                    athlete_lines = [
                        compact(item)
                        for item in (packed_rank.group("athletes") or "").splitlines()
                        if compact(item)
                    ]
                    total = next((cell for cell in reversed(cells) if score_tokens(cell)), None)
                    for athlete_line in athlete_lines:
                        gender = None
                        gender_match = re.match(r"(?P<name>.+?)\s+(?P<gender>[MF])$", athlete_line)
                        athlete_name = athlete_line
                        if gender_match:
                            athlete_name = compact(gender_match.group("name"))
                            gender = gender_match.group("gender")
                        records.append(
                            result_record(
                                page,
                                event,
                                round_name,
                                rank,
                                " | ".join(cells),
                                athlete_name=athlete_name,
                                team_name=team_name,
                                gender=gender,
                                total=total,
                                score_detail={"table_cells": cells},
                                confidence="medium",
                            )
                        )
                    continue

                if not cells[0].isdigit() or len(cells) < 4:
                    continue
                rank = cells[0]
                bib_no = cells[1] if len(cells) > 1 and cells[1].isdigit() else None
                name = cells[2] if len(cells) > 2 else None
                noc_code = cells[3] if len(cells) > 3 and re.fullmatch(r"[A-Z]{3}", cells[3]) else None
                total = next((cell for cell in reversed(cells) if score_tokens(cell)), None)
                records.append(
                    result_record(
                        page,
                        event,
                        round_name,
                        rank,
                        " | ".join(cells),
                        bib_no=bib_no,
                        athlete_name=name,
                        noc_code=noc_code,
                        total=total,
                        score_detail={"table_cells": cells},
                        confidence="medium",
                    )
                )

    if not records:
        warnings.append("no_parseable_rank_rows")
    if not event:
        warnings.append("event_not_inferred")
    if not round_name:
        warnings.append("round_not_inferred")
    return records, warnings


def parse_pages(pages: list[dict[str, Any]]) -> tuple[list[dict[str, Any]], list[dict[str, Any]], list[dict[str, Any]]]:
    athletes: list[dict[str, Any]] = []
    results: list[dict[str, Any]] = []
    audit: list[dict[str, Any]] = []

    for page in pages:
        year = games_year(page)
        page_number = page["page"]["page_number"]
        page_type = required_page_type(year, page_number, page["content"]["text"])
        if not page_type:
            continue

        event, round_name = extract_event_round(page, page_type)
        warnings: list[str] = []
        parsed_count = 0
        if page_type == "Entry List by NOC":
            records, warnings = parse_entry_list(page)
            athletes.extend(records)
            parsed_count = len(records)
        elif page_type == "ASC Ranking Points Results":
            records, warnings = parse_ranking_page(page)
            athletes.extend(records)
            parsed_count = len(records)
        elif page_type == "Results":
            records, warnings = parse_results_page(page)
            results.extend(records)
            parsed_count = len(records)

        audit.append(
            {
                **source_base(page, page_type),
                "classification": page_type,
                "event": event,
                "round": round_name,
                "parsed_record_count": parsed_count,
                "table_count": page["content"].get("table_count", 0),
                "word_count": page["content"].get("word_count", 0),
                "warnings": warnings,
            }
        )

    return athletes, results, audit


def main() -> None:
    args = parse_args()
    pages = load_pages(args.input_dir)
    athletes, results, audit = parse_pages(pages)

    athlete_count = write_jsonl(args.output_dir / "asian_games_athletes.jsonl", athletes)
    result_count = write_jsonl(args.output_dir / "asian_games_results.jsonl", results)
    audit_count = write_jsonl(args.output_dir / "asian_games_parse_audit.jsonl", audit)

    print(f"Wrote {athlete_count} athlete records")
    print(f"Wrote {result_count} result records")
    print(f"Wrote {audit_count} audit records")


if __name__ == "__main__":
    main()
